version: '3.8'

services:
  grpc-utils:
    image: ghcr.io/ortoo/node-services:18-bullseye
    volumes:
      - ..:/workspace:delegated
    init: true

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity